Repository QUANTAXIS/QUANTAXIS, pull requests merged in 2018-06, with the labels that each got.

#494 QA_DataStruct_Indicators 增加指标类
  CHANGELOG.md
  QUANTAXIS/QAARP/QARisk.py
  QUANTAXIS/QAData/QAIndicatorStruct.py
  QUANTAXIS/QAData/__init__.py
  QUANTAXIS/__init__.py
  test_backtest/simplebacktest.py
Labels: help wanted, in progress

#496 QAQuery_Advance 中函数的参数检查 和 注释
  CHANGELOG.md
  QUANTAXIS/QAData/QAFinancialStruct.py
  QUANTAXIS/QAFetch/QAQuery_Advance.py
Labels: in progress

#495 update financial
  QUANTAXIS/QAData/QAFinancialStruct.py
Labels: in progress

#497 QAQuery_Advance 中函数的参数检查 和 注释
  QUANTAXIS/QAFetch/QAQuery_Advance.py
  QUANTAXIS_Test/QAData_Test/quotation_base_test.py
  QUANTAXIS_Test/QAUtil_Test/QADate_Test.py
  QUANTAXIS_Test/QAUtil_Test/QADate_trade_Test.py
  requirements.txt
  test_backtest/strategy_qsdd.py
Labels: in progress

#498 QAQuery_Advance 中函数 去掉了 rest index 的判断None
  QUANTAXIS/QAFetch/QAQuery_Advance.py
Labels: in progress

#499 update 指标类
  CHANGELOG.md
  Documents/indicators.md
  QUANTAXIS/QAData/QAIndicatorStruct.py
  QUANTAXIS/QAData/base_datastruct.py
  README.md
Labels: Epic, FIXED, enhancement, help wanted, in progress

#500 #update CHANGELOG
  CHANGELOG.md
  QUANTAXIS/__init__.py
Labels: in progress

#501 update indicators doc
  Documents/indicators.md
Labels: in progress

#502 #fix doc
  Documents/indicators.md
Labels: in progress

#503 #udpate
  Documents/indicators.md
Labels: in progress

#504 # PR DOC UPDATE
  Documents/about_pr.md
Labels: in progress

#505 #update README.md
  README.md
Labels: in progress

#507 ADD ISSUE TEMPLEATE
  .github/ISSUE_TEMPLATE/quantaxis_issue.md
Labels: in progress

#508 quantaxis 命令行 save 命令错误的 异常处理
  CHANGELOG.md
  QUANTAXIS/QACmd/__init__.py
  QUANTAXIS/QACmd/backtest.py
  QUANTAXIS/QAFetch/QAQuery_Advance.py
  QUANTAXIS/QAFetch/QATushare.py
  QUANTAXIS/QASU/main.py
  QUANTAXIS/QASU/save_tdx.py
  QUANTAXIS_Test/QABacktest_Test/QABacktest_GuppyAverageMovementLines.py
  QUANTAXIS_Test/QAFetch_Test/QAQuery_Advance_Test.py
  QUANTAXIS_Test/QAUtil_Test/QATest_None.py
Labels: in progress

#510 QA_Risk 插件增加对于assets计算的修改(如果撮合按不复权撮合,risk也按不复权去计算assets)
  CHANGELOG.md
  QUANTAXIS/QAARP/QARisk.py
Labels: in progress

#511 #update
  CHANGELOG.md
  QUANTAXIS/QAData/base_datastruct.py
  QUANTAXIS/__init__.py
Labels: in progress

#512 update for open browser after install
  CHANGELOG.md
  setup.py
Labels: in progress

#513 fix bug for select_code
  CHANGELOG.md
  QUANTAXIS/QAData/base_datastruct.py
  QUANTAXIS/__init__.py
Labels: in progress

#514 命令行添加了 save stock_info_tushare
  CHANGELOG.md
  QUANTAXIS/QAARP/QAPortfolio.py
  QUANTAXIS/QAARP/QAUser.py
  QUANTAXIS/QACmd/__init__.py
  QUANTAXIS/QAFetch/QAQuery.py
  QUANTAXIS/QAFetch/QATdx.py
  QUANTAXIS/QASU/main.py
  QUANTAXIS/QASU/save_backtest.py
  QUANTAXIS/QASU/save_tdx.py
  QUANTAXIS/QASU/save_tushare.py
  QUANTAXIS/QASU/user.py
  QUANTAXIS_Test/QAFetch_Test/QAQuery_Advance_Test.py
  QUANTAXIS_Test/QAFetch_Test/QAQuery_Test.py
Labels: in progress

#515 update
  CHANGELOG.md
  QUANTAXIS/QAData/base_datastruct.py
  QUANTAXIS/QAMarket/QABacktestBroker.py
  QUANTAXIS/QAMarket/shipaneBroker.py
Labels: in progress

#517 对于basedatastruct的修改和更新
  CHANGELOG.md
  QUANTAXIS/QAData/base_datastruct.py
Labels: in progress

#519 大幅修改 base_datastruct方法的 select_time_by_gap, splits, add_func方法,优化性能
  CHANGELOG.md
  QUANTAXIS/QAData/base_datastruct.py
Labels: in progress

#520 update for format of test_file
  QUANTAXIS_Test/QAARP_Test/QAAccount_Test.py
  QUANTAXIS_Test/QAARP_Test/QAUser_Test.py
  QUANTAXIS_Test/QAAnalysis_Test/QAAnalysis_dataframe_Test.py
  QUANTAXIS_Test/QABacktest_Test/QABacktestSimple_Test.py
  QUANTAXIS_Test/QABacktest_Test/QABacktest_GuppyAverageMovementLines.py
  QUANTAXIS_Test/QABacktest_Test/QABacktest_Test.py
  QUANTAXIS_Test/QAData_Test/quotation_base_test.py
  QUANTAXIS_Test/QAEngine_Test/QAEvent_Test.py
  QUANTAXIS_Test/QAFetch_Test/Fetcher_Test.py
  QUANTAXIS_Test/QAFetch_Test/QAQuery_Advance_Test.py
  QUANTAXIS_Test/QAFetch_Test/QAQuery_Test.py
  QUANTAXIS_Test/QAFetch_Test/QATdx_Test.py
  QUANTAXIS_Test/QAMarket_Test/QA_Order_Test.py
  QUANTAXIS_Test/QAUtil_Test/QADate_trade_Test.py
  QUANTAXIS_Test/QAUtil_Test/QATest_None.py
  QUANTAXIS_Test/QAUtil_Test/QATester_nothing.py
Labels: in progress

#524 修改账户密码
  QUANTAXIS_Trade/WYFFuture/crerathapi/base.py
  QUANTAXIS_Trade/WYFFuture/crerathapi/config.py
  QUANTAXIS_Trade/WYFFuture/crerathapi/jy.py
  QUANTAXIS_Trade/WYFFuture/crerathapi/main.py
  QUANTAXIS_Trade/WYFFuture/crerathapi/main_old.py
  QUANTAXIS_Trade/WYFFuture/crerathapi/test.py
  QUANTAXIS_Trade/WYFFuture/crerathapi/trade.py
  QUANTAXIS_Trade/WYFFuture/crerathapi/tradeapi.py
Labels: in progress

#525 期货下单接口测试ok
  QUANTAXIS/QAARP/QARisk.py
  QUANTAXIS_Test/QABacktest_Test/QABacktest_GuppyAverageMovementLines.py
  QUANTAXIS_Trade/WYFFuture/crerathapi/DialogRsp.con
  QUANTAXIS_Trade/WYFFuture/crerathapi/Private.con
  QUANTAXIS_Trade/WYFFuture/crerathapi/Public.con
  QUANTAXIS_Trade/WYFFuture/crerathapi/QueryRsp.con
  QUANTAXIS_Trade/WYFFuture/crerathapi/TradingDay.con
  QUANTAXIS_Trade/WYFFuture/crerathapi/config.py
  QUANTAXIS_Trade/WYFFuture/crerathapi/jy.py
  QUANTAXIS_Trade/WYFFuture/crerathapi/main.py
  QUANTAXIS_Trade/WYFFuture/crerathapi/trade.py
  QUANTAXIS_Trade/WYFFuture/crerathapi/tradeapi.py
Labels: in progress

#526 #update config to absoult path
  QUANTAXIS_Trade/WYFFuture/crerathapi/config.py
Labels: in progress

#527 quantaxis__db_description
  QUANTAXIS/QAFetch/QAQuery.py
  QUANTAXIS/QASU/save_to_db_fields_description.py
  QUANTAXIS/QASU/save_tushare.py
  QUANTAXIS_Test/QAFetch_Test/QAQuery_Advance_Test.py
  QUANTAXIS_Test/QAFetch_Test/QAQuery_Test.py
Labels: in progress

#528 #del emoji in save
  QUANTAXIS/QASU/save_tdx.py
  QUANTAXIS_Test/QAData_Test/quotation_base_test.py
Labels: in progress

#529 CHANGE BETTER CODE HUB TEST FILE YML
  .bettercodehub.yml
Labels: in progress

#534 复权 量的修正
  CHANGELOG.md
  QUANTAXIS/QABacktest/QAT0Backtest.py
  QUANTAXIS/QAData/data_fq.py
  QUANTAXIS/QAUtil/QAParameter.py
Labels: in progress

#535 实盘易下单对接
  CHANGELOG.md
  QUANTAXIS/QAMarket/shipaneBroker.py
Labels: in progress

#533 添加读取钱龙本地文件读取
  .gitignore
  QUANTAXIS_Test/QAFetch_Test/QAQuery_Advance_Test.py
  QUANTAXIS_Test/QAFetch_Test/readme.md
Labels: in progress

#574 update
  CHANGELOG.md
  QUANTAXIS/QAFetch/QATdx.py
  QUANTAXIS/QAFetch/QATradeFile.py
  QUANTAXIS/QAUtil/QASetting.py
  test_backtest/QUANTAXIS回测分析全过程讲解.ipynb
  test_backtest/QUANTAXIS回测分析全过程讲解.md
  test_backtest/TEST_ ORDER_ BACKTEST.ipynb
  test_backtest/TEST_ ORDER_ BACKTEST.md
  test_backtest/output_36_0.png
  test_backtest/output_40_0.png
Labels: in progress

#575 #update
  CHANGELOG.md
  QUANTAXIS/QASU/save_tdx.py
Labels: in progress

#576 #
  QUANTAXIS/QAFetch/QATdx.py
  QUANTAXIS/QASU/save_tdx.py
Labels: in progress

#578 钱龙数据 股份变动 WGT的数据格式
  QUANTAXIS/QASU/save_to_db_fields_description.py
  QUANTAXIS/QAUtil/QASetting.py
  QUANTAXIS_Test/QAFetch_Test/QAQuery_Advance_Test.py
  QUANTAXIS_Test/QAUtil_Test/QATest_None.py
  QUANTAXIS_Test/QAUtil_Test/QATester_nothing.py
Labels: in progress

#579 update min_backtest
  CHANGELOG.md
  QUANTAXIS/QAARP/QAAccount.py
  QUANTAXIS/QABacktest/QABacktest.py
  QUANTAXIS/QABacktest/QAT0Backtest.py
  QUANTAXIS/QAData/QADataStruct.py
  QUANTAXIS/QAData/base_datastruct.py
  QUANTAXIS/QAEngine/QAThreadEngine.py
  QUANTAXIS/QAMarket/QABacktestBroker.py
  docker/dockerfile
  test_backtest/minstrategy.py
  test_backtest/strategy.py
Labels: in progress

#580 update
  CHANGELOG.md
  QUANTAXIS/QAEngine/QAAsyncioEngine.py
  QUANTAXIS/QAEngine/QAProcessEngine.py
  QUANTAXIS/QAEngine/QAUvloopEnging.py
  QUANTAXIS/QAMarket/QAMarket.py
  test_backtest/backtest.py
  test_backtest/strategy.py
Labels: in progress

#584 update accounts
  CHANGELOG.md
  QUANTAXIS/QAARP/QAAccount.py
  QUANTAXIS/QAARP/QAPortfolio.py
  QUANTAXIS/QAARP/QARisk.py
  QUANTAXIS/QAAnalysis/QAAnalysis_trade.py
  QUANTAXIS/QABacktest/QAT0Backtest.py
  QUANTAXIS/__init__.py
  README.md
  test_backtest/QUANTAXIS回测分析全过程讲解.ipynb
  test_backtest/TEST_ ORDER(BACKTEST+T0).ipynb
  test_backtest/TEST_ ORDER(BACKTEST+T0).md
  test_backtest/TEST_ ORDER_ BACKTEST.ipynb
  test_backtest/backtest.py
Labels: in progress

#585 update gitattributes
  .gitattributes
Labels: in progress

#587 update T0 backtest
  CHANGELOG.md
  QUANTAXIS/QAARP/QAAccount.py
  QUANTAXIS/QABacktest/QABacktest.py
  QUANTAXIS/QAMarket/QAMarket.py
  README.md
  test_backtest/T0backtest.ipynb
  test_backtest/T0backtest.py
Labels: in progress

#588 T0回测撮合
  CHANGELOG.md
  QUANTAXIS/QAARP/QAAccount.py
  QUANTAXIS/QAMarket/QABacktestBroker.py
  test_backtest/T0backtest.ipynb
  test_backtest/T0backtest.py
  test_backtest/strategy.py
Labels: in progress

#589 #使用随机买卖测试t0框架
  CHANGELOG.md
  test_backtest/T0backtest.ipynb
Labels: in progress

#590 增加对于多个标的的t0账户的支持 修复bug
  CHANGELOG.md
  QUANTAXIS/QAARP/QAAccount.py
  QUANTAXIS/QABacktest/QABacktest.py
  test_backtest/T0backtest.ipynb
Labels: in progress

#591 update to 1.0.48
  CHANGELOG.md
  QUANTAXIS/QAARP/QAAccount.py
  QUANTAXIS/QAARP/QAPortfolio.py
  QUANTAXIS/QAFetch/QAQuery_Advance.py
  QUANTAXIS/__init__.py
  test_backtest/T0backtest.ipynb
  test_backtest/TEST_ ORDER(BACKTEST+T0).ipynb
Labels: in progress

#592 update to 1.0.49
  CHANGELOG.md
  QUANTAXIS/QAARP/QARisk.py
  QUANTAXIS/__init__.py
Labels: in progress

#595 #update for broker
  QUANTAXIS/QAMarket/shipaneBroker.py
  jupyterexample/QA_MARKETENGINE.py
Labels: in progress

#597 update risk_doc
  Documents/risk.md
  QUANTAXIS/QAARP/QARisk.py
  SUMMARY.md
Labels: in progress

#599 docker doc
  docker/readme.md
Labels: in progress

#600 #update docker file
  docker/dockerfile
  docker/mongo.sh
  docker/mongo/dockerfile
Labels: in progress

#602 #update requirements
  requirements.txt
  setup.py
Labels: in progress

#604 #update doc
  .gitignore
  Documents/crawler.md
  SUMMARY.md
Labels: in progress

#605 #update doc
  Documents/crawler.md
Labels: in progress

#608 #update 实时数据推送 8010端口
  QUANTAXIS/QAWeb/index.html
Labels: in progress

#609 1.0.50 release
  CHANGELOG.md
  QUANTAXIS/QAFetch/QATdx.py
  QUANTAXIS/QAFetch/__init__.py
  QUANTAXIS/QAUtil/QAWebutil.py
  QUANTAXIS/QAUtil/__init__.py
  QUANTAXIS/QAWeb/QA_Web.py
  QUANTAXIS/QAWeb/__init__.py
  QUANTAXIS/QAWeb/backtest/__init__.py
  QUANTAXIS/QAWeb/backtest/handles.py
  QUANTAXIS/QAWeb/basehandles.py
  QUANTAXIS/QAWeb/data/__init__.py
  QUANTAXIS/QAWeb/datahandles.py
  QUANTAXIS/QAWeb/fetch_block.py
  QUANTAXIS/QAWeb/quotation/__init__.py
  QUANTAXIS/QAWeb/quotation/websocket.md
  QUANTAXIS/QAWeb/quotationhandles.py
  QUANTAXIS/QAWeb/user/__init__.py
  QUANTAXIS/QAWeb/userhandles.py
  QUANTAXIS/QAWeb/util/__init__.py
  QUANTAXIS/QAWeb/util/fetch_block.py
  QUANTAXIS/__init__.py
  docs/lib/QUANTAXIS/QAUtil/__init__.py
  index.html
  job_list.md
  source/QUANTAXIS.QAUtil.rst
Labels: in progress

#610 #update for func
  QUANTAXIS/__init__.py
Labels: in progress

#611 #change 1.0.51 ==> 1.0.52
  CHANGELOG.md
  QUANTAXIS/__init__.py
Labels: in progress

#612 #update
  QUANTAXIS/QAWeb/QA_Web.py
  QUANTAXIS/QAWeb/basehandles.py
  QUANTAXIS/QAWeb/quotationhandles.py
Labels: in progress

#614 setup在未安装不应该import QUANTAXIS
  QUANTAXIS/QAFetch/QAbinance.py
  QUANTAXIS/QASU/save_binance.py
  setup.py
Labels: in progress

#615 QA_fetch_stock_list_adv bug
  QUANTAXIS/QACmd/__init__.py
  QUANTAXIS/QAFetch/QAQuery_Advance.py
Labels: in progress

#617 save binance按照utc时间
  QUANTAXIS/QACmd/__init__.py
  QUANTAXIS/QAFetch/QAbinance.py
  QUANTAXIS/QASU/save_binance.py
Labels: in progress

#622 update to 1.0.53
  CHANGELOG.md
  QUANTAXIS/__init__.py
  README.md
Labels: in progress

#623 #UPDATE FOR LOWMEMORY
  QUANTAXIS/QAFetch/QAfinancial.py
  QUANTAXIS/QASU/save_local.py
  QUANTAXIS/__init__.py
Labels: in progress

#624 优化了save financialfiles 的逻辑
  CHANGELOG.md
  QUANTAXIS/QASU/main.py
  QUANTAXIS/QASU/save_local.py
  QUANTAXIS/__init__.py
Labels: in progress

#626 优化了 crawl eastmoney zjlx all 的命令
  CHANGELOG.md
  QUANTAXIS/QACmd/__init__.py
  QUANTAXIS/QASU/crawl_eastmoney.py
  QUANTAXIS/QASU/main.py
  QUANTAXIS/QASU/save_to_db_fields_description.py
  QUANTAXIS_CRAWLY/eastmoney_simulation_web_trader.py
  QUANTAXIS_CRAWLY/run_selenium_alone.py
  QUANTAXIS_CRAWLY_TEST/eastmoney_simulation_web_trader_test.py
  QUANTAXIS_Test/QAData_Test/data_fq_test.py
  QUANTAXIS_Test/QAFetch_Test/QACrawl_Test.py
Labels: in progress

#627 #update curio
  QUANTAXIS/QAEngine/QACurioEngine.py
  QUANTAXIS/QAWeb/fetch_block.py
  conf.py
Labels: in progress

#628 shipane
  QUANTAXIS/QAMarket/shipaneBroker.py
  QUANTAXIS_CRAWLY/QUANTAXIS_SCRAPY_FETCH/settings.py
Labels: in progress

#629 update save financialfiles/ pr templates
  CHANGELOG.md
  PULL_REQUEST_TEMPLATE.md
  QUANTAXIS/QACmd/__init__.py
  QUANTAXIS/QASU/main.py
Labels: in progress

#630 update 期货数据
  CHANGELOG.md
  QUANTAXIS/QAFetch/__init__.py
  QUANTAXIS/__init__.py
  jupyterexample/QAFetch.ipynb
Labels: in progress

#631 # update setup.py for travis CI
  setup.py
Labels: in progress

#632 修改了QAWeb的获取数据优先级,避免在无mongodb的时候的```connection timeout```问题
  CHANGELOG.md
  QUANTAXIS/QAARP/QAAccount.py
  QUANTAXIS/QAMarket/shipaneBroker.py
  QUANTAXIS/QAUtil/QAError.py
  QUANTAXIS/QAUtil/QAParameter.py
  QUANTAXIS/QAWeb/fetch_block.py
  QUANTAXIS/__init__.py
Labels: in progress

#633 #update
  QUANTAXIS/QAARP/QAAccount.py
  QUANTAXIS/QAARP/QARisk.py
  QUANTAXIS/QAData/financial_mean.py
  QUANTAXIS/QAUtil/QASetting.py
Labels: in progress

#634 #update for QAARP
  CHANGELOG.md
  QUANTAXIS/QAARP/QAAccount.py
  QUANTAXIS/QAARP/QARisk.py
Labels: in progress

#635 ##update to 1.0.57
  CHANGELOG.md
  QUANTAXIS/QACmd/__init__.py
  QUANTAXIS/QAMarket/QABacktestBroker.py
  QUANTAXIS/__init__.py
  setup.py
Labels: in progress

#636 change to 1.0.58
  CHANGELOG.md
  QUANTAXIS/__init__.py
  setup.py
Labels: in progress

#638 1. QA_Account 增加hold_time属性, 显示持仓时间 2. 对于QA_Query 的 QA_fetch_financialfiles进行修改, 优化返回结果
  CHANGELOG.md
  Documents/about_event.py
  Documents/about_updatedata.md
  Documents/database.md
  QUANTAXIS/QAARP/QAAccount.py
  QUANTAXIS/QAFetch/QAQuery.py
  QUANTAXIS/QAFetch/QAQuery_Advance.py
  QUANTAXIS/QAWeb/tradehandles.py
Labels: in progress

#639 update QABlockanme
  CHANGELOG.md
  QUANTAXIS/QAARP/QAAccount.py
  QUANTAXIS/QAData/QADataStruct.py
  QUANTAXIS/QAData/financial_mean.py
Labels: in progress

#640 #update
  QUANTAXIS/QAData/QADataStruct.py
Labels: in progress

#641 #update xtp_rules/errors
  Documents/xtp_error.md
  Documents/xtp_rules.md
Labels: in progress

#643 update for documents
  CHANGELOG.md
  Documents/DataStruct.md
  Documents/QUANTAXIS回测分析全过程讲解.md
  Documents/TEST_ORDER_BACKTEST_T0.md
  Documents/output_22_1.png
  Documents/output_34_1.png
  Documents/output_35_1.png
  Documents/output_36_0.png
  Documents/output_37_0.png
  Documents/output_38_0.png
  Documents/output_40_0.png
  QUANTAXIS/QAAnalysis/QAAnalysis_block.py
  QUANTAXIS/QAData/QABlockStruct.py
  QUANTAXIS/QAData/QADataStruct.py
  QUANTAXIS/QAData/__init__.py
  QUANTAXIS/QAFetch/QAQuery.py
  QUANTAXIS/QAFetch/QAfinancial.py
  QUANTAXIS/QAMarket/shipaneBroker.py
  QUANTAXIS/__init__.py
  SUMMARY.md
  setup.py
Labels: in progress

#644 #update
  CHANGELOG.md
  QUANTAXIS/QAData/__init__.py
  QUANTAXIS/QAData/dsmethods.py
  QUANTAXIS/__init__.py
Labels: in progress

#645 #update dsmethods
  QUANTAXIS/QAData/dsmethods.py
Labels: in progress

#646 #update for vol check
  QUANTAXIS/QAData/base_datastruct.py
  QUANTAXIS/QAData/dsmethods.py
Labels: in progress

#647 #update doc
  CHANGELOG.md
  Documents/install.md
  Documents/usejupyter.md
  SUMMARY.md
Labels: in progress

#648 #update 缓存服务器--> pic.yutiansut.com
  CONTRIBUTING.md
  Documents/DataStruct.md
  Documents/about_event.md
  Documents/about_market.md
  Documents/about_pr.md
  Documents/docker.md
  Documents/install.md
  Documents/usejupyter.md
  README.md
  README_ENG.md
  docker/readme.md
Labels: in progress

#649 mac 下 财务数据无法读取的问题
  Documents/install.md
  QUANTAXIS/QAFetch/QAfinancial.py
  QUANTAXIS/QASU/crawl_eastmoney.py
  QUANTAXIS/QASU/save_local.py
  QUANTAXIS_CRAWLY/run_selenium_alone.py
  QUANTAXIS_Test/QAData_Test/data_fq_test.py
  README.md
Labels: in progress

#650 update to 1.0.59
  CHANGELOG.md
  QUANTAXIS/QAData/QADataStruct.py
  QUANTAXIS/QAMarket/shipaneBroker.py
  QUANTAXIS/__init__.py
Labels: in progress

#651 update to 1.0.60
  CHANGELOG.md
  QUANTAXIS/QAData/QADataStruct.py
  QUANTAXIS/QAData/base_datastruct.py
Labels: in progress

#655 完善撤单接口
  QUANTAXIS/QAMarket/shipaneBroker.py
Labels: in progress

#656 QARISK/QAPERFORMACE 更新, QAFETCH 大幅更新
  CHANGELOG.md
  QUANTAXIS/QAARP/QARisk.py
  QUANTAXIS/QAFetch/QATdx.py
  QUANTAXIS/QAFetch/__init__.py
  QUANTAXIS/QAMarket/QAShipaneBroker.py
  QUANTAXIS/QATrade/QATradeRealtime.py
  QUANTAXIS/QAUtil/QAError.py
  QUANTAXIS/QAUtil/QAParameter.py
  QUANTAXIS/QAUtil/QASetting.py
  QUANTAXIS/__init__.py
  README.md
  setup.py
Labels: in progress

#657 @update linux ctp
  CHANGELOG.md
  QUANTAXIS_Trade/LINUXCTP/CTPMarketSpi.py
  QUANTAXIS_Trade/LINUXCTP/CTPTraderSpi.py
  QUANTAXIS_Trade/LINUXCTP/DataStruct.py
  QUANTAXIS_Trade/LINUXCTP/Event.py
  README.md
Labels: in progress

#658 #update readme
  QUANTAXIS_Trade/LINUXCTP/readme.md
Labels: in progress

#660 #update test
  QUANTAXIS_Trade/LINUXCTP/test.py
Labels: in progress

#659 简化函数
  QUANTAXIS/QACmd/__init__.py
  QUANTAXIS/QAFetch/QAbinance.py
  QUANTAXIS/QASU/save_binance.py
  QUANTAXIS/QAUtil/QAcrypto.py
Labels: in progress

#661 振幅修改
  QUANTAXIS/QAData/base_datastruct.py
Labels: in progress
