Repository QUANTAXIS/QUANTAXIS, pull requests merged in 2019-04, with the labels that each got.

#1080 添加QA_fetch_get_index_latest，加速最后一天日线的获取数据
  QUANTAXIS/QAFetch/QATdx.py
Labels: in progress

#1082 增加回测结果任意区间查看功能
  QUANTAXIS/QAARP/QARisk.py
Labels: in progress

#1081 update: 减少对于account的智障获取
  EXAMPLE/2_类的测试与讲解/QAACCOUNT 保证金冻结释放测试.ipynb
  EXAMPLE/4_回测实盘交易/QA_MARKETENGINE.py
  EXAMPLE/4_回测实盘交易/回测/期货回测/future_min_backtest.py
  EXAMPLE/4_回测实盘交易/回测/股票回测/基于QAMARKET的回测/backtest.py
  EXAMPLE/4_回测实盘交易/回测/股票回测/多季度选股择时回测.py
  EXAMPLE/4_回测实盘交易/回测/股票回测/简易回测/MACD_JCSC.py
  EXAMPLE/4_回测实盘交易/回测/股票回测/简易回测/simple_minbacktest.py
  EXAMPLE/4_回测实盘交易/回测/股票回测/简易回测/simplebacktest.py
  EXAMPLE/4_回测实盘交易/回测/股票回测/超级简化版回测/MACD_JCSC.py
  EXAMPLE/4_回测实盘交易/回测/股票回测/超级简化版回测/simple_minbacktest.py
  EXAMPLE/4_回测实盘交易/回测/股票回测/超级简化版回测/simplebacktest.py
  EXAMPLE/4_回测实盘交易/回测/股票日内交易回测/T0backtest.py
  EXAMPLE/test_backtest/T0backtest.py
  EXAMPLE/test_backtest/TEST_ ORDER(stock+T0+Future).ipynb
  QUANTAXIS/QAARP/QAPortfolio.py
  QUANTAXIS/QAApplication/QABacktest.py
  releaseNote.md
Labels: QUANTAXIS ENHANCEMENT, enhancement, in progress

#1085 fix bug and update to 1.3.7
  QUANTAXIS/QAARP/QAPortfolio.py
  QUANTAXIS/QAFetch/QATdx_adv.py
  QUANTAXIS/__init__.py
Labels: in progress

#1084 Add 获取期货合约详情的方法
  QUANTAXIS/QAARP/market_preset.py
Labels: in progress

#1086 把tts的设置放到config文件中， 更新QA_TTSBroker的DEMO，增加与QAMarket结合使用的DEMO
  EXAMPLE/4_回测实盘交易/QATTS_caitong_test.py
  EXAMPLE/4_回测实盘交易/QATTS_caitong_with_QAMarket.ipynb
  QUANTAXIS/QAFetch/QATdx.py
  QUANTAXIS/QAMarket/QAMarket.py
  QUANTAXIS/QAMarket/QATTSBroker.py
Labels: in progress

#1087 update fix bug for portfolio
  QUANTAXIS/QAARP/QAPortfolio.py
Labels: in progress

#1088 fix account bug
  QUANTAXIS/QAARP/QAAccount.py
  QUANTAXIS/QAARP/QARisk.py
  QUANTAXIS/__init__.py
Labels: in progress

#1089 修正port必须为int型的bug
  QUANTAXIS/QAMarket/QATTSBroker.py
Labels: in progress

#1090 update for commission fee
  QUANTAXIS/QAARP/market_preset.py
  QUANTAXIS/__init__.py
Labels: in progress

#1091 update
  QUANTAXIS/QAARP/QARisk.py
  QUANTAXIS/__init__.py
Labels: in progress

#1092 #update a new open/close for pnl
  QUANTAXIS/QAARP/QARisk.py
Labels: in progress

#1093 为quantaxisq增加sleep参数，为timeout和sleep参数增加类型转换
  QUANTAXIS/QAFetch/QAQuery.py
  QUANTAXIS/QAFetch/QATdx_adv.py
Labels: in progress

#1094 试图解决的 多进程读写出错问题
  QUANTAXIS/QAFetch/QATdx.py
  QUANTAXIS/QAMarket/QAShipaneBroker.py
  QUANTAXIS/QAUtil/QALogs.py
  QUANTAXIS/QAUtil/QASetting.py
  QUANTAXIS/QAUtil/QASql.py
  QUANTAXIS/__init__.py
  setup.py
Labels: QUANTAXIS ENHANCEMENT, QUANTAXIS Modify, Watching, enhancement, in progress

#1098 Update QARisk.py,增加对贝塔计算的兼容处理
  QUANTAXIS/QAARP/QARisk.py
Labels: in progress

#1099 增加现有持仓的成本价计算，用于模拟盘时实盘
  QUANTAXIS/QAARP/QAAccount.py
Labels: in progress

#1100 update
  QUANTAXIS/QAARP/QARisk.py
  QUANTAXIS/QAUtil/QALogs.py
  QUANTAXIS/QAUtil/QASetting.py
Labels: in progress

#1101 QAAccount的历史记录存储增加开平标志/ QAPerformance的字段更新改进
  QUANTAXIS/QAARP/QAAccount.py
  QUANTAXIS/QAARP/QARisk.py
  QUANTAXIS/__init__.py
  QUANTAXIS_Test/QAARP_Test/mytest_QAAccount.py
Labels: QUANTAXIS ENHANCEMENT, QUANTAXIS Modify, enhancement, in progress

#1102 重构QA_Tdx_Executor的队列维护
  QUANTAXIS/QAFetch/QATdx_adv.py
Labels: in progress

#1103 加强对于几万个回测账户时的 user的加载速度
  QUANTAXIS/QAARP/QAPortfolio.py
Labels: in progress

#1104 修改中断形式
  QUANTAXIS/QAFetch/QATdx_adv.py
Labels: in progress

#1105 update performance
  QUANTAXIS/QAARP/QARisk.py
Labels: in progress

#1107 RANK for QUANTAXIS ACCOUNT!
  QUANTAXIS/QAARP/QARisk.py
  QUANTAXIS/QAARP/market_preset.py
  QUANTAXIS/QAAnalysis/QAAnalysis_account.py
  QUANTAXIS/QAFetch/QAQuery.py
Labels: enhancement, in progress

#1109 回滚多余的监测代码，仅保留索引效率和解决卡住
  QUANTAXIS/QAFetch/QATdx_adv.py
Labels: in progress

#1110 update
  Documents/TECH/P0_Head.md
  Documents/TECH/P1_Prepare.md
  Documents/TECH/P2_Scenario.md
  Documents/TECH/P3_Backtest.md
  Documents/TECH/P4_Analysis.md
  Documents/TECH/P5_REALTIME.md
  Documents/TECH/P6_Thought.md
  QUANTAXIS/QAFetch/QAQuery.py
Labels: in progress

#1111 update STU
  Documents/TECH/P0_Head.md
  STU/P0_Head.md
  STU/P1_Prepare.md
  STU/P2_Scenario.md
  STU/P3_Backtest.md
  STU/P4_Analysis.md
  STU/P5_REALTIME.md
  STU/P6_Thought.md
Labels: in progress

#1112 #update to 1.4.3
  EXAMPLE/4_回测实盘交易/回测/期货回测/future_min_backtest.py
  QUANTAXIS/QAARP/QARisk.py
  QUANTAXIS/__init__.py
Labels: in progress

#1113 #update Examples
  EXAMPLE/4_回测实盘交易/回测/股票回测/简易回测/MACD_JCSC.py
  EXAMPLE/4_回测实盘交易/回测/股票回测/简易回测/simple_minbacktest.py
  EXAMPLE/4_回测实盘交易/回测/股票回测/超级简化版回测/MACD_JCSC.py
  EXAMPLE/4_回测实盘交易/回测/股票回测/超级简化版回测/simple_minbacktest.py
Labels: in progress

#1114 update P1
  STU/P1_Prepare.md
Labels: in progress

#1115 update
  STU/P1_Prepare.md
Labels: in progress

#1117 update : fix talib indicator bug
  QUANTAXIS/QAIndicator/talib_indicators.py
  STU/P1_Prepare.md
Labels: in progress

#1119 update a cython accelerate
  .gitignore
  QUANTAXIS/QAARP/QAAccount.c
  QUANTAXIS/QAARP/QAAccount.cp36-win_amd64.pyd
  QUANTAXIS/QAARP/QAAccount.pyx
  QUANTAXIS/__init__.py
  README.md
  STU/P3_Backtest.md
  setup_cython.py
Labels: in progress

#1121 #update account pyx
  QUANTAXIS/QAARP/QAAccount.c
  QUANTAXIS/QAARP/QAAccount.cp36-win_amd64.pyd
  QUANTAXIS/QAARP/QAAccount.pyx
  QUANTAXIS/QAMarket/QAOrder.c
  QUANTAXIS/QAMarket/QAOrder.cp36-win_amd64.pyd
  QUANTAXIS/QAMarket/QAOrder.pyx
  QUANTAXIS/QAUtil/QAParameter.pyx
  setup_cython.py
Labels: in progress

#1123 修改tts以适应cython
  QUANTAXIS/QAMarket/QATTSBroker.py
Labels: in progress

#1122 优化ip选择方式
  QUANTAXIS/QAFetch/QATdx.py
Labels: in progress

#1127 update doc
  Documents/QAAccount.md
  EXAMPLE/2_类的测试与讲解/QAAccount.ipynb
  QUANTAXIS/Exp/Qrpc.py
  QUANTAXIS/Exp/__init__.py
  SUMMARY.md
Labels: in progress

#1130 update
  EXAMPLE/2_类的测试与讲解/QAAccount.ipynb
  QUANTAXIS/QAARP/QAAccount.py
  QUANTAXIS/QAARP/QAUser.py
  QUANTAXIS/QAARP/market_preset.py
  QUANTAXIS/QAMarket/QAPosition.py
  QUANTAXIS/QAMarket/__init__.py
  QUANTAXIS/QAUtil/QAParameter.py
  QUANTAXIS/QAUtil/__init__.py
  QUANTAXIS/__init__.py
Labels: in progress

#1132 update
  Documents/TEST_ORDER_BACKTEST_T0.md
  EXAMPLE/test_backtest/TEST_ ORDER(stock+T0+Future).ipynb
  QUANTAXIS/QAARP/QAAccount.c
  QUANTAXIS/QAARP/QAAccount.py
  QUANTAXIS/QAARP/QAAccount.pyx
  QUANTAXIS/QAEngine/QAThreadEngine.py
  QUANTAXIS/QAMarket/QAOrder.c
  QUANTAXIS/QAMarket/QAOrder.py
  QUANTAXIS/QAMarket/QAOrder.pyx
  QUANTAXIS/QAMarket/QAOrderHandler.py
  QUANTAXIS/QAMarket/QAOrderHandler_async.py
  QUANTAXIS/QAMarket/QAPosition.py
  QUANTAXIS/QAMarket/__init__.py
  QUANTAXIS/__init__.py
Labels: in progress

#1131 解耦和统一了k(quotation)/tick/realtime的获取方法,增加了默认值
  QUANTAXIS/QAFetch/Fetcher.py
Labels: in progress

#1133 update for QAPOSITION
  QUANTAXIS/QAMarket/QAPosition.py
Labels: in progress

#1134 rolling back from QAOMS to QA_OrderQueue / fix QAPositon
  Documents/TEST_ORDER_BACKTEST_T0.md
  EXAMPLE/test_backtest/TEST_ ORDER(stock+T0+Future).ipynb
  QUANTAXIS/QAARP/QAAccount.c
  QUANTAXIS/QAARP/QAAccount.py
  QUANTAXIS/QAARP/QAAccount.pyx
  QUANTAXIS/QAMarket/QAOrder.c
  QUANTAXIS/QAMarket/QAOrder.py
  QUANTAXIS/QAMarket/QAOrder.pyx
  QUANTAXIS/QAMarket/QAOrderHandler.py
  QUANTAXIS/QAMarket/QAOrderHandler_async.py
  QUANTAXIS/QAMarket/QAPosition.py
  QUANTAXIS/QAMarket/__init__.py
  QUANTAXIS/__init__.py
Labels: enhancement, in progress

#1135 update
  QUANTAXIS/QAMarket/QAPosition.py
Labels: in progress

#1136 update
  QUANTAXIS/QAARP/QAAccount.py
  QUANTAXIS/QAMarket/QAPosition.py
Labels: in progress

#1137 #update pos
  QUANTAXIS/QAMarket/QAPosition.py
  setup.py
Labels: in progress

#1138 update
  QUANTAXIS/QAMarket/QAPosition.py
Labels: in progress

#1139 update to 1.4.5
  QUANTAXIS/QAARP/market_preset.py
  QUANTAXIS/QAMarket/QAPosition.py
  QUANTAXIS/__init__.py
Labels: in progress

#1140 #update PMS EXAMPLE
  EXAMPLE/5_测试特性_不稳定/QAPMS.ipynb
  QUANTAXIS/Exp/asyncschedule.py
  QUANTAXIS/Exp/asynctask.py
  QUANTAXIS/Exp/test_async.py
  QUANTAXIS/QAARP/QAAccount.c
  QUANTAXIS/QAARP/QAAccount.py
  QUANTAXIS/QAARP/QAAccount.pyx
  QUANTAXIS/QAMarket/QAPosition.py
Labels: in progress

#1141 #update
  EXAMPLE/5_测试特性_不稳定/QAPMS.ipynb
Labels: in progress

#1142 update AsyncExec
  EXAMPLE/5_测试特性_不稳定/QAPMS.ipynb
  QUANTAXIS/Exp/asyncschedule.py
  QUANTAXIS/Exp/asynctask.py
  QUANTAXIS/Exp/test_async.py
  QUANTAXIS/QAMarket/QAPosition.py
Labels: in progress

#1143 Super update: ASYNC ENGINE
  QUANTAXIS/Exp/test_async.py
  QUANTAXIS/QAEngine/asyncexec.py
  QUANTAXIS/QAEngine/asyncschedule.py
  QUANTAXIS/QAEngine/asynctask.py
  QUANTAXIS/__init__.py
Labels: in progress

#1146 新增一个异步线程执行器 超级牛逼 QA_AsyncThread
  QUANTAXIS/Exp/test_async.py
  QUANTAXIS/QAEngine/QAAsyncThread.py
  QUANTAXIS/QAEngine/asyncexec.py
  QUANTAXIS/__init__.py
Labels: in progress

#1145 添加新的select best ip的方法为默认选取ip的方法
  QUANTAXIS/QAFetch/QATdx.py
Labels: in progress

#1147 #update to 1.4.8
  QUANTAXIS/__init__.py
  setup.py
Labels: in progress
